### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by KhagayN** [mskilab/skitools#3]
There are functions in the current version of gUtils such as gr.pairflip that require certain functions such as gr.flip. That function is not in the Feb. version of gUtils so will skitools become a dependency of gUtils or should I add gr.flip to gUtils?

**Comment by mskilab** [comment]
I think gr.pairflip should depend on gr.flipstrand - but check with
Jeremiah since I've never used gr.pairflip before ..

**Comment by KhagayN** [comment]
oh I see, gr.flip and gr.flipstrand refer to the same function. This happened for cross-compatibility?

**Comment by mskilab** [comment]
Yup exactly  - I was using gr.flip but Jeremiah switched to gr.flipstrand
(maybe for compatibility with gr.stripstrand) ..
