### ISSUE TITLE
Running skitools

### ISSUE THREAD

**Issue by KhagayN** [mskilab/skitools#4]
There are some functions in skitools that won't be able to run b/c they depend on functions in either gTrack or gUtils. Just to double check, skitools is serving as a home for functions that might be used but, not as a stand alone package?

**Comment by mskilab** [comment]
skitools is basically a private package for mskilab + friends, so we can
treat it as a temporary or permanent dumping ground for functions that
don't have a home elsewhere

It's fine for skitools to depend on gUtils and gTrack, but not vice versa

**Comment by KhagayN** [comment]
Understood. thanks.
